name: Azure Deployment

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: "Choose environment"
        required: true
        options:
          - Test
          - Prod
env:
  DIST_DIR: dist
  BICEP_FILES: src/rg/main-rg.bicep
  
permissions:
  id-token: write
  contents: read
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # full history for tags

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        auth-type: SERVICE_PRINCIPAL

    - name: Install Bicep cli & Build Bicep files to JSON
      run: |
        set -euo pipefail
        az bicep install
        mkdir -p $DIST_DIR
        az bicep build --file "$BICEP_FILES" --outdir "$DIST_DIR"

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/main-rg.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     
  
