name: azure deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  BICEP_FILES: src/rg/main-rg.bicep
  DOC_DIR: doc
  DIST_DIR: _site

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: SERVICE_PRINCIPAL

      - name: Install Bicep CLI & Build Bicep JSON
        run: |
          az bicep install
          mkdir -p $DOC_DIR
          az bicep build --file "$BICEP_FILES" --outdir "$DOC_DIR"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build Jekyll site
        uses: actions/jekyll-build-pages@v1
        with:
          source: ${{ env.DOC_DIR }}/main-rg.json
          destination: ${{ env.DIST_DIR }}/main-rg.json

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ env.DIST_DIR }}/main-rg.json

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
