name: Azure Deployment to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: "Choose environment"
        required: true
        options:
          - Test
          - Prod

env:
  DIST_DIR: dist
  BICEP_FILES: src/rg/main-rg.bicep

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        auth-type: SERVICE_PRINCIPAL

    - name: Install Bicep CLI & Build files
      run: |
        set -euo pipefail
        az bicep install
        mkdir -p $DIST_DIR
        az bicep build --file "$BICEP_FILES" --outdir "$DIST_DIR"

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ env.DIST_DIR }}

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
