name: Conditional Azure Deployment

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: "Choose environment"
        required: true
        options:
          - Test
          - Prod
      operation:
        type: choice
        description: "Operation to perform"
        required: true
        options:
          - create-resource-group
permissions:
  id-token: write
  contents: read
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        auth-type: SERVICE_PRINCIPAL

    - name: Deploy Bicep if operation is create-resource-group
      if: inputs.operation == 'create-resource-group'
      run: |
        az deployment sub what-if --name create-rg-deployment  --subscription {{ secret.AZURE_SUBSCRIPTION_ID }} --template-file src/rg/main-rg.bicep --parameters resourceGroupName='rg-azure-testing-${{ inputs.env }}' location='eastus'
